# Generated by Django 5.2.3 on 2025-06-29 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0002_competencia_capacidad_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacidad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='capacidad',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='nota',
            name='capacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academica.capacidad'),
        ),
    ]
