# Generated by Django 5.2.3 on 2025-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0003_remove_capacidad_descripcion_capacidad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
