# Generated by Django 4.2.11 on 2025-07-02 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0007_nivel_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academica.nivel'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
