# Generated by Django 4.2.11 on 2025-07-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0009_remove_usuario_rol_alter_profesor_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tardanza', 'Tardanza')], max_length=10),
        ),
    ]
